ERRALL.LS      Robot Name ROBOT 20-NOV-25 19:46:50  

1" 20-NOV-25 19:46:48 " R E S E T                                         " "                               00000000"    "
2" 20-NOV-25 19:46:42 " SYST-040 Operation mode AUTO Selected             " " SERVO                         00110110"    "
3" 20-NOV-25 19:46:42 " TPIF-157 Menu cannot be displayed                 " " WARN                          00000000"    "
4" 20-NOV-25 19:46:30 " SYST-305 System startup in progress               " " SERVO                         00110110"    "
5" 20-NOV-25 19:46:28 " SYST-042 DEADMAN defeated                         " " SERVO                         00110110"    "
6" 20-NOV-25 19:46:28 " SYST-305 System startup in progress               " " STOP.G                        00100110"    "
7" 20-NOV-25 19:46:28 " R E S E T                                         " "                               00000000"    "
8" 20-NOV-25 19:46:28 " SRVO-307 HBK close/HBK enabled (G:1)              " " WARN                          00000000"    "
9" 20-NOV-25 19:46:24 " SYST-026 System normal power up                   " " WARN                          00000000"    "
10" 20-NOV-25 19:45:54 " OPTN-018 No CUSTO additions on this media         " " WARN                          00000000"    "
11" 20-NOV-25 19:45:54 " OPTN-018 No Language additions on this media      " " WARN                          00000000"    "
