LOGBOOK.LS     Robot Name ROBOT 25-NOV-25 22:59:52  

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Operation        
========================================
FILE 'LETESZ.TP' is saved              
25-NOV-25 22:59 :52
========================================
FILE 'IRC_STLABEL.VR' is saved         
25-NOV-25 22:59 :52
========================================
FILE 'IRC_STATUS.VR' is saved          
25-NOV-25 22:59 :52
========================================
FILE 'IRC_MSG.VR' is saved             
25-NOV-25 22:59 :52
========================================
FILE 'IRC_COUNTER.VR' is saved         
25-NOV-25 22:59 :52
========================================
FILE 'IPKDMP.ZIP' is saved             
25-NOV-25 22:59 :52
========================================
FILE 'IOSTATUS.CM' is saved            
25-NOV-25 22:59 :52
========================================
FILE 'HTTPKCL.VR' is saved             
25-NOV-25 22:59 :52
========================================
FILE 'HTCOLREC.VR' is saved            
25-NOV-25 22:59 :52
========================================
FILE 'HIST.LS' is saved                
25-NOV-25 22:59 :52
========================================
FILE 'GETDATA.TP' is saved             
25-NOV-25 22:59 :52
========================================
FILE 'GEMDATA.VR' is saved             
25-NOV-25 22:59 :52
========================================
FILE 'FTPLOG.DG' is saved              
25-NOV-25 22:59 :52
========================================
FILE 'FRAMEVAR.VR' is saved            
25-NOV-25 22:59 :52
========================================
FILE 'FLEXUIF.XML' is saved            
25-NOV-25 22:59 :52
========================================
FILE 'FELVESZ.TP' is saved             
25-NOV-25 22:59 :50
========================================
FILE 'ETHERNET.DG' is saved            
25-NOV-25 22:59 :50
========================================
FILE 'ERRSYS.LS' is saved              
25-NOV-25 22:59 :50
========================================
FILE 'ERRPWD.LS' is saved              
25-NOV-25 22:59 :50
========================================
FILE 'ERRMOT.LS' is saved              
25-NOV-25 22:59 :50
========================================
FILE 'ERRHIST.LS' is saved             
25-NOV-25 22:59 :50
========================================
FILE 'ERREXT.LS' is saved              
25-NOV-25 22:59 :50
========================================
FILE 'ERRCURR.LS' is saved             
25-NOV-25 22:59 :50
========================================
FILE 'ERRCOMM.LS' is saved             
25-NOV-25 22:59 :50
========================================
FILE 'ERRAPP.LS' is saved              
25-NOV-25 22:59 :50
========================================
FILE 'ERRALL.LS' is saved              
25-NOV-25 22:59 :50
========================================
FILE 'ERRACT.LS' is saved              
25-NOV-25 22:59 :50
========================================
FILE 'EMAIL.DG' is saved               
25-NOV-25 22:59 :50
========================================
FILE 'DIOCFGSV.IO' is saved            
25-NOV-25 22:59 :50
========================================
FILE 'DF_MOTN0.DF' is saved            
25-NOV-25 22:59 :50
========================================
FILE 'DF_LOGI6.DF' is saved            
25-NOV-25 22:59 :50
========================================
FILE 'DF_LOGI5.DF' is saved            
25-NOV-25 22:59 :50
========================================
FILE 'DF_LOGI4.DF' is saved            
25-NOV-25 22:59 :50
========================================
FILE 'DF_LOGI3.DF' is saved            
25-NOV-25 22:59 :50
========================================
FILE 'DF_LOGI2.DF' is saved            
25-NOV-25 22:59 :50
========================================
FILE 'DF_LOGI1.DF' is saved            
25-NOV-25 22:59 :50
========================================
FILE 'DCSVRFY.DG' is saved             
25-NOV-25 22:59 :50
========================================
FILE 'DCSDIFF.DG' is saved             
25-NOV-25 22:59 :50
========================================
FILE 'DCSCHG03.DG' is saved            
25-NOV-25 22:59 :50
========================================
FILE 'DCSCHG02.DG' is saved            
25-NOV-25 22:59 :50
========================================
FILE 'DCSCHG01.DG' is saved            
25-NOV-25 22:59 :50
========================================
FILE 'CONSLOG.DG' is saved             
25-NOV-25 22:59 :50
========================================
FILE 'COMSET.VR' is saved              
25-NOV-25 22:59 :50
========================================
FILE 'CELLIO.SV' is saved              
25-NOV-25 22:59 :50
========================================
FILE 'BICSETUP.VR' is saved            
25-NOV-25 22:59 :50
========================================
FILE 'BACKDATE.DT' is saved            
25-NOV-25 22:59 :50
========================================
FILE 'ATERRJOB.VR' is saved            
25-NOV-25 22:59 :50
========================================
FILE '-BCKEDT-.TP' is saved            
25-NOV-25 22:59 :50
========================================
FILE '-BCKED9-.TP' is saved            
25-NOV-25 22:59 :50
========================================
FILE '-BCKED8-.TP' is saved            
25-NOV-25 22:59 :50
========================================
FILE 'LETESZ.TP' is saved              
25-NOV-25 22:59 :50
========================================
FILE 'LETESZ.LS' is loaded             
25-NOV-25 22:59 :50
========================================
FILE 'FELVESZ.TP' is saved             
25-NOV-25 22:59 :50
========================================
FILE 'FELVESZ.LS' is loaded            
25-NOV-25 22:59 :50
========================================
R E S E T                              
                                       
                              00000000 
25-NOV-25 22:59 :42
========================================
Override 100%                          
25-NOV-25 22:59 :42
========================================
Menu changed 'UTILITIES Hints'         
25-NOV-25 22:59 :34
========================================
Override 10%                           
25-NOV-25 22:59 :34
========================================
FILE 'MEMORY.DG' is saved              
25-NOV-25 22:59 :32
========================================
SYST-176 Software was updated          
                                       
                                       
PAUSE.G                       00100010 
25-NOV-25 22:59 :32
========================================
FILE 'ERRALL.LS' is saved              
25-NOV-25 22:59 :32
========================================
FILE 'FRS:\CMIO.VR' is loaded          
25-NOV-25 22:59 :32
========================================
SYST-042 DEADMAN defeated              
                                       
                                       
SERVO                         00110110 
25-NOV-25 22:59 :30
========================================
R E S E T                              
                                       
                              00000000 
25-NOV-25 22:59 :30
========================================
Cold start                             
25-NOV-25 22:59 :24
========================================
'START (COLD)' is selected in FCTN     
25-NOV-25 22:59 :22
========================================
Menu changed ''                        
25-NOV-25 22:59 :20
========================================
'S/W INSTALL' is selected in MENU      
25-NOV-25 22:59 :20
========================================
Menu changed ''                        
25-NOV-25 22:59 :14
========================================
User frame 50(G:1)                     
25-NOV-25 22:59 :14
========================================
Tool frame 83(G:1)                     
25-NOV-25 22:59 :14
========================================
FILE 'MEMORY.DG' is saved              
25-NOV-25 22:59 :12
========================================
SYST-290 Cycle power to use new DCS par
ameter                                 
                                       
STOP.G                        00100110 
25-NOV-25 22:59 :12
========================================
FILE 'MED:\00\TEMP\DF_MOTN0.DF' is load
ed                                     
25-NOV-25 22:59 :12
========================================
FILE 'MED:\00\TEMP\DF_LOGI6.DF' is load
ed                                     
25-NOV-25 22:59 :12
========================================
FILE 'MED:\00\TEMP\DF_LOGI5.DF' is load
ed                                     
25-NOV-25 22:59 :12
========================================
FILE 'MED:\00\TEMP\DF_LOGI4.DF' is load
ed                                     
25-NOV-25 22:59 :12
========================================
FILE 'MED:\00\TEMP\DF_LOGI3.DF' is load
ed                                     
25-NOV-25 22:59 :12
========================================
FILE 'MED:\00\TEMP\DF_LOGI2.DF' is load
ed                                     
25-NOV-25 22:59 :12
========================================
FILE 'MED:\00\TEMP\DF_LOGI1.DF' is load
ed                                     
25-NOV-25 22:59 :12
========================================
FILE 'MED:\00\TEMP\PROG1.TP' is loaded 
25-NOV-25 22:59 :12
========================================
FILE 'MED:\00\TEMP\LETESZ.TP' is loaded
25-NOV-25 22:59 :12
========================================
FILE 'MED:\00\TEMP\FELVESZ.TP' is loade
d                                      
25-NOV-25 22:59 :12
========================================
FILE 'MED:\00\TEMP\-BCKEDT-.TP' is load
ed                                     
25-NOV-25 22:59 :12
========================================
FILE 'MED:\00\TEMP\-BCKED9-.TP' is load
ed                                     
25-NOV-25 22:59 :12
========================================
FILE 'MED:\00\TEMP\-BCKED8-.TP' is load
ed                                     
25-NOV-25 22:59 :12
========================================
FILE 'TPEINS.XML' is loaded            
25-NOV-25 22:59 :12
========================================
FILE 'TBSWRC65.VR' is loaded           
25-NOV-25 22:59 :12
========================================
FILE 'SWIUPDT.VR' is loaded            
25-NOV-25 22:59 :12
========================================
FILE 'STRREG.VR' is loaded             
25-NOV-25 22:59 :12
========================================
FILE 'POSREG.VR' is loaded             
25-NOV-25 22:59 :12
========================================
FILE 'NUMREG.VR' is loaded             
25-NOV-25 22:59 :12
========================================
FILE 'IRC_STLABEL.VR' is loaded        
25-NOV-25 22:59 :12
========================================
FILE 'IRC_STATUS.VR' is loaded         
25-NOV-25 22:59 :12
========================================
FILE 'IRC_MSG.VR' is loaded            
25-NOV-25 22:59 :12
========================================
FILE 'IRC_COUNTER.VR' is loaded        
25-NOV-25 22:59 :12
========================================
FILE 'HTTPKCL.VR' is loaded            
25-NOV-25 22:59 :12
========================================
FILE 'HTCOLREC.VR' is loaded           
25-NOV-25 22:59 :12
========================================
FILE 'GEMDATA.VR' is loaded            
25-NOV-25 22:59 :12
========================================
FILE 'FRAMEVAR.VR' is loaded           
25-NOV-25 22:59 :12
========================================
FILE 'COMSET.VR' is loaded             
25-NOV-25 22:59 :10
========================================
FILE 'BICSETUP.VR' is loaded           
25-NOV-25 22:59 :10
========================================
FILE 'ATERRJOB.VR' is loaded           
25-NOV-25 22:59 :10
========================================
FILE 'TPSCRN.ZIP' is loaded            
25-NOV-25 22:59 :10
========================================
FILE 'SYSPASS.SV' is loaded            
25-NOV-25 22:59 :10
========================================
FILE 'SYSHOST.SV' is loaded            
25-NOV-25 22:59 :10
========================================
FILE 'SYSFSAC.SV' is loaded            
25-NOV-25 22:59 :10
========================================
FILE 'FLEXUIF.XML' is loaded           
25-NOV-25 22:59 :10
========================================
FILE 'RC65.DT' is loaded               
25-NOV-25 22:59 :10
========================================
FILE 'CELLIO.SV' is loaded             
25-NOV-25 22:59 :10
========================================
FILE 'MIXLOGIC.SV' is loaded           
25-NOV-25 22:59 :10
========================================
FILE 'EMAIL.DG' is loaded              
25-NOV-25 22:59 :10
========================================
FILE 'POSREG.VR' is loaded             
25-NOV-25 22:59 :10
========================================
FILE 'SYSUIF.SV' is loaded             
25-NOV-25 22:59 :10
========================================
FILE 'STRREG.VR' is loaded             
25-NOV-25 22:59 :10
========================================
FILE 'SYSFRAME.SV' is loaded           
25-NOV-25 22:59 :10
========================================
FILE 'SYSMACRO.SV' is loaded           
25-NOV-25 22:59 :10
========================================
FILE 'SYSMAST.SV' is loaded            
25-NOV-25 22:59 :10
========================================
FILE 'SYSSERVO.SV' is loaded           
25-NOV-25 22:59 :10
========================================
FILE 'DIOCFGSV.IO' is loaded           
25-NOV-25 22:59 :10
========================================
FILE 'NUMREG.VR' is loaded             
25-NOV-25 22:59 :10
========================================
FILE 'FRAMEVAR.VR' is loaded           
25-NOV-25 22:59 :10
========================================
SYST-040 Operation mode AUTO Selected  
                                       
                                       
SERVO                         00110110 
25-NOV-25 22:59 :08
========================================
FILE 'SYSVARS.SV' is loaded            
25-NOV-25 22:59 :08
========================================
FILE 'MFS:\RLOPRC65.PC' is loaded      
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\OPSETUP.PC' is loaded       
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\ABCRC65.VR' is loaded       
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\ABCSETUP.PC' is loaded      
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\RLSPRC65.PC' is loaded      
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\DGRC65.VR' is loaded        
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\DGSETUP.PC' is loaded       
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\WASETUP.PC' is loaded       
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\MSRC65.VR' is loaded        
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\MSSETUP.PC' is loaded       
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\AARC65.VR' is loaded        
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\AASETUP.PC' is loaded       
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\RLSTHSCD.PC' is loaded      
25-NOV-25 22:58 :34
========================================
FILE 'PATH:\SVRC65.VR' is loaded       
25-NOV-25 22:58 :34
========================================
FILE 'PATH:\RLSETSV.PC' is loaded      
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\DCRC65.VR' is loaded        
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\DCSETUP.PC' is loaded       
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\PLRC65.VR' is loaded        
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\PIRC65.VR' is loaded        
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\PISETUP.PC' is loaded       
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\TJRC65.VR' is loaded        
25-NOV-25 22:58 :34
========================================
FILE 'PATH:\RLSETTBJ.PC' is loaded     
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\TLRC65.VR' is loaded        
25-NOV-25 22:58 :34
========================================
FILE 'PATH:\RLSETTBC.PC' is loaded     
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\SMRC65.VR' is loaded        
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\SMSETUP.PC' is loaded       
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\MURC65.VR' is loaded        
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\MUSETUP.PC' is loaded       
25-NOV-25 22:58 :34
========================================
FILE 'MFS:\RVSETUP.PC' is loaded       
25-NOV-25 22:58 :34
========================================
FILE 'PATH:\RLSVRC65.PC' is loaded     
25-NOV-25 22:58 :34
========================================
Control start                          
25-NOV-25 22:58 :28
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
I/O              
========================================
 SO[    3]    ON  -> OFF
Tick:   4607
TB:     846654493
25-NOV-25 22:59 :42
========================================
 UO[    6]    ON  -> OFF
Tick:   4605
TB:     846637709
25-NOV-25 22:59 :42
========================================
 SO[    0]    ON  -> OFF
Tick:   4481
TB:     842963046
25-NOV-25 22:59 :40
========================================
 UO[    2]    OFF -> ON 
Tick:   1056
TB:     756424347
25-NOV-25 22:59 :32
========================================
 UO[    6]    OFF -> ON 
Tick:   1042
TB:     741242934
25-NOV-25 22:59 :30
========================================
 UO[   17]    OFF
 UO[   18]    OFF
 UO[   19]    OFF
 UO[   20]    OFF
 UO[   21]    OFF
 UO[   22]    OFF
 UO[   23]    OFF
 UO[   24]    OFF
 UO[   33]    OFF
 UO[   34]    OFF
 UO[   35]    OFF
 UO[   36]    OFF
Tick:   1015
TB:     739832765
25-NOV-25 22:59 :30
========================================
 AO[    1]    0
 AO[    3]    0
 AO[    3]    0
 AO[    5]    0
 AO[    5]    0
 AO[    7]    0
 UI[    1]    ON 
 UI[    2]    ON 
 UI[    3]    ON 
 UI[    4]    OFF
 UI[    5]    OFF
 UI[    6]    OFF
 UI[    7]    OFF
 UI[    8]    ON 
 UI[   17]    OFF
 UI[   18]    OFF
 UI[   19]    OFF
 UI[   20]    OFF
 UI[   21]    OFF
 UI[   22]    OFF
 UI[   23]    OFF
 UI[   24]    OFF
 UI[   33]    OFF
 UI[   34]    OFF
 UO[    1]    OFF
 UO[    2]    OFF
 UO[    3]    OFF
 UO[    4]    OFF
 UO[    5]    OFF
 UO[    6]    OFF
 UO[    7]    OFF
 UO[    8]    OFF
Tick:   1014
TB:     739831967
25-NOV-25 22:59 :30
========================================
 AI[   15]    0
 AI[   17]    0
 AI[   13]    0
 AI[   15]    0
 AI[   17]    0
 AI[   19]    0
 AI[   21]    0
 AI[   23]    0
Tick:   1013
TB:     739831606
25-NOV-25 22:59 :30
========================================
 AI[    5]    0
 AI[    7]    0
 AI[    9]    0
 AI[   11]    0
 AI[    7]    0
 AI[    9]    0
 AI[   11]    0
 AI[   13]    0
Tick:   1012
TB:     738293882
25-NOV-25 22:59 :30
========================================
 DO[   49]    OFF
 DO[   50]    OFF
 DO[   51]    OFF
 DO[   52]    OFF
 DO[   53]    OFF
 DO[   54]    OFF
 DO[   55]    OFF
 DO[   56]    OFF
 DO[   57]    OFF
 DO[   58]    OFF
 DO[   59]    OFF
 DO[   60]    OFF
 DO[   61]    OFF
 DO[   62]    OFF
 DO[   63]    OFF
 DO[   64]    OFF
 DO[   65]    OFF
 DO[   66]    OFF
 DO[   67]    OFF
 DO[   68]    OFF
 DO[   69]    OFF
 DO[   70]    OFF
 DO[   71]    OFF
 DO[   72]    OFF
 DO[   73]    OFF
 DO[   74]    OFF
 DO[   75]    OFF
 DO[   76]    OFF
 DO[   77]    OFF
 DO[   78]    OFF
 DO[   79]    OFF
 DO[   80]    OFF
 DO[   81]    OFF
 DO[   82]    OFF
 DO[   83]    OFF
 DO[   84]    OFF
 DO[   85]    OFF
 DO[   86]    OFF
 DO[   87]    OFF
 DO[   88]    OFF
 DO[   89]    OFF
 DO[   90]    OFF
 DO[   91]    OFF
 DO[   92]    OFF
 DO[   93]    OFF
 DO[   94]    OFF
 DO[   95]    OFF
 DO[   96]    OFF
 DO[   97]    OFF
 DO[   98]    OFF
 DO[   99]    OFF
 DO[  100]    OFF
 DO[  101]    OFF
 DO[  102]    OFF
 DO[  103]    OFF
 DO[  104]    OFF
 DO[  105]    OFF
 DO[  106]    OFF
 DO[  107]    OFF
 DO[  108]    OFF
 DO[  109]    OFF
 DO[  110]    OFF
 DO[  111]    OFF
 DO[  112]    OFF
 DO[  113]    OFF
 DO[  114]    OFF
 DO[  115]    OFF
 DO[  116]    OFF
 DO[  117]    OFF
 DO[  118]    OFF
 DO[  119]    OFF
 DO[  120]    OFF
 DO[  121]    OFF
 DO[  122]    OFF
 DO[  123]    OFF
 DO[  124]    OFF
 DO[  125]    OFF
 DO[  126]    OFF
 DO[  127]    OFF
 DO[  128]    OFF
 DO[  129]    OFF
 DO[  130]    OFF
 DO[  131]    OFF
 DO[  132]    OFF
 DO[  133]    OFF
 DO[  134]    OFF
 DO[  135]    OFF
 DO[  136]    OFF
 DO[  137]    OFF
 DO[  138]    OFF
 DO[  139]    OFF
 DO[  140]    OFF
 DO[  141]    OFF
 DO[  142]    OFF
 DO[  143]    OFF
 DO[  144]    OFF
 AI[    1]    0
 AI[    3]    0
Tick:   1011
TB:     738261765
25-NOV-25 22:59 :30
========================================
 DI[   65]    OFF
 DI[   66]    OFF
 DI[   67]    OFF
 DI[   68]    OFF
 DI[   69]    OFF
 DI[   70]    OFF
 DI[   71]    OFF
 DI[   72]    OFF
 DI[   73]    OFF
 DI[   74]    OFF
 DI[   75]    OFF
 DI[   76]    OFF
 DI[   77]    OFF
 DI[   78]    OFF
 DI[   79]    OFF
 DI[   80]    OFF
 DI[   81]    OFF
 DI[   82]    OFF
 DI[   83]    OFF
 DI[   84]    OFF
 DI[   85]    OFF
 DI[   86]    OFF
 DI[   87]    OFF
 DI[   88]    OFF
 DI[   89]    OFF
 DI[   90]    OFF
 DI[   91]    OFF
 DI[   92]    OFF
 DI[   93]    OFF
 DI[   94]    OFF
 DI[   95]    OFF
 DI[   96]    OFF
 DI[   97]    OFF
 DI[   98]    OFF
 DI[   99]    OFF
 DI[  100]    OFF
 DI[  101]    OFF
 DI[  102]    OFF
 DI[  103]    OFF
 DI[  104]    OFF
 DI[  105]    OFF
 DI[  106]    OFF
 DI[  107]    OFF
 DI[  108]    OFF
 DI[  109]    OFF
 DI[  110]    OFF
 DI[  111]    OFF
 DI[  112]    OFF
 DI[  113]    OFF
 DI[  114]    OFF
 DI[  115]    OFF
 DI[  116]    OFF
 DI[  117]    OFF
 DI[  118]    OFF
 DI[  119]    OFF
 DI[  120]    OFF
 DI[  121]    OFF
 DI[  122]    OFF
 DI[  123]    OFF
 DI[  124]    OFF
 DI[  125]    OFF
 DI[  126]    OFF
 DI[  127]    OFF
 DI[  128]    OFF
 DI[  129]    OFF
 DI[  130]    OFF
 DI[  131]    OFF
 DI[  132]    OFF
 DI[  133]    OFF
 DI[  134]    OFF
 DI[  135]    OFF
 DI[  136]    OFF
 DI[  137]    OFF
 DI[  138]    OFF
 DI[  139]    OFF
 DI[  140]    OFF
 DI[  141]    OFF
 DI[  142]    OFF
 DI[  143]    OFF
 DI[  144]    OFF
 DO[   21]    OFF
 DO[   22]    OFF
 DO[   23]    OFF
 DO[   24]    OFF
 DO[   25]    OFF
 DO[   26]    OFF
 DO[   27]    OFF
 DO[   28]    OFF
 DO[   37]    OFF
 DO[   38]    OFF
 DO[   39]    OFF
 DO[   40]    OFF
 DO[   41]    OFF
 DO[   42]    OFF
 DO[   43]    OFF
 DO[   44]    OFF
 DO[   53]    OFF
 DO[   54]    OFF
 DO[   55]    OFF
 DO[   56]    OFF
 DO[   25]    OFF
 DO[   26]    OFF
 DO[   27]    OFF
 DO[   28]    OFF
 DO[   29]    OFF
 DO[   30]    OFF
 DO[   31]    OFF
 DO[   32]    OFF
 DO[   33]    OFF
 DO[   34]    OFF
 DO[   35]    OFF
 DO[   36]    OFF
 DO[   37]    OFF
 DO[   38]    OFF
 DO[   39]    OFF
 DO[   40]    OFF
 DO[   41]    OFF
 DO[   42]    OFF
 DO[   43]    OFF
 DO[   44]    OFF
 DO[   45]    OFF
 DO[   46]    OFF
 DO[   47]    OFF
 DO[   48]    OFF
Tick:   1010
TB:     738261257
25-NOV-25 22:59 :30
========================================
 SI[    0]    ON 
 SI[    1]    OFF
 SI[    2]    ON 
 SI[    3]    ON 
 SI[    4]    OFF
 SI[    5]    OFF
 SI[    6]    OFF
 SI[    7]    OFF
 SI[    8]    ON 
 SI[    9]    ON 
 SI[   10]    OFF
 SI[   11]    OFF
 SI[   12]    OFF
 SI[   13]    OFF
 SI[   14]    OFF
 SI[   15]    OFF
 SO[    0]    ON 
 SO[    1]    OFF
 SO[    2]    OFF
 SO[    3]    ON 
 SO[    4]    OFF
 SO[    5]    OFF
 SO[    6]    OFF
 SO[    7]    OFF
 SO[    8]    OFF
 SO[    9]    OFF
 SO[   10]    OFF
 SO[   11]    OFF
 SO[   12]    OFF
 SO[   13]    OFF
 SO[   14]    OFF
 SO[   15]    OFF
 RI[    1]    OFF
 RI[    2]    OFF
 RI[    3]    OFF
 RI[    4]    OFF
 RI[    5]    OFF
 RI[    6]    OFF
 RI[    7]    OFF
 RI[    8]    OFF
 RO[    1]    OFF
 RO[    2]    OFF
 RO[    3]    OFF
 RO[    4]    OFF
 RO[    5]    OFF
 RO[    6]    OFF
 RO[    7]    OFF
 RO[    8]    OFF
SSI[    1]    OFF
SSI[    2]    OFF
SSI[    3]    OFF
SSI[    4]    OFF
SSI[    5]    OFF
SSI[    6]    OFF
SSI[    7]    OFF
SSI[    8]    OFF
SSI[    9]    OFF
SSI[   10]    OFF
SSI[   11]    OFF
SSI[   12]    OFF
SSI[   13]    OFF
 DI[   19]    OFF
 DI[   20]    OFF
 DI[   21]    OFF
 DI[   22]    OFF
 DI[   23]    OFF
 DI[   24]    OFF
 DI[   25]    OFF
 DI[   26]    OFF
 DI[   35]    OFF
 DI[   36]    OFF
 DI[   37]    OFF
 DI[   38]    OFF
 DI[   39]    OFF
 DI[   40]    OFF
 DI[   41]    OFF
 DI[   42]    OFF
 DI[   51]    OFF
 DI[   52]    OFF
 DI[   53]    OFF
 DI[   54]    OFF
 DI[   55]    OFF
 DI[   56]    OFF
 DI[   25]    OFF
 DI[   26]    OFF
 DI[   27]    OFF
 DI[   28]    OFF
 DI[   29]    OFF
 DI[   30]    OFF
 DI[   31]    OFF
 DI[   32]    OFF
 DI[   33]    OFF
 DI[   34]    OFF
 DI[   35]    OFF
 DI[   36]    OFF
 DI[   37]    OFF
 DI[   38]    OFF
 DI[   39]    OFF
 DI[   40]    OFF
 DI[   41]    OFF
 DI[   42]    OFF
 DI[   43]    OFF
 DI[   44]    OFF
 DI[   45]    OFF
 DI[   46]    OFF
 DI[   47]    OFF
 DI[   48]    OFF
 DI[   49]    OFF
 DI[   50]    OFF
 DI[   51]    OFF
 DI[   52]    OFF
 DI[   53]    OFF
 DI[   54]    OFF
 DI[   55]    OFF
 DI[   56]    OFF
 DI[   57]    OFF
 DI[   58]    OFF
 DI[   59]    OFF
 DI[   60]    OFF
 DI[   61]    OFF
 DI[   62]    OFF
 DI[   63]    OFF
 DI[   64]    OFF
Tick:   1009
TB:     738260460
25-NOV-25 22:59 :30
