ERRSYS.LS      Robot Name ROBOT 20-NOV-25 19:46:54  

1" 20-NOV-25 19:46:42 " SYST-040 Operation mode AUTO Selected             " " SERVO                         00110110" 
2" 20-NOV-25 19:46:42 " TPIF-157 Menu cannot be displayed                 " " WARN                          00000000" 
3" 20-NOV-25 19:46:30 " SYST-305 System startup in progress               " " SERVO                         00110110" 
4" 20-NOV-25 19:46:28 " SYST-042 DEADMAN defeated                         " " SERVO                         00110110" 
5" 20-NOV-25 19:46:28 " SYST-305 System startup in progress               " " STOP.G                        00100110" 
6" 20-NOV-25 19:46:24 " SYST-026 System normal power up                   " " WARN                          00000000" 
7" 20-NOV-25 19:45:54 " OPTN-018 No CUSTO additions on this media         " " WARN                          00000000" 
8" 20-NOV-25 19:45:54 " OPTN-018 No Language additions on this media      " " WARN                          00000000" 
