ERRMOT.LS      Robot Name ROBOT 20-NOV-25 19:44:44  

1" 20-NOV-25 19:31:36 " JOG -013 Stroke limit (G:1 A:5)                   " " WARN                          00000000" 
2" 20-NOV-25 19:31:32 " JOG -013 Stroke limit (G:1 A:5)                   " " WARN                          00000000" 
3" 20-NOV-25 19:28:34 " JOG -013 Stroke limit (G:1 A:5)                   " " WARN                          00000000" 
4" 20-NOV-25 19:23:06 " JOG -013 Stroke limit (G:1 A:5)                   " " WARN                          00000000" 
5" 20-NOV-25 19:22:56 " JOG -013 Stroke limit (G:1 A:5)                   " " WARN                          00000000" 
6" 20-NOV-25 19:22:52 " JOG -013 Stroke limit (G:1 A:5)                   " " WARN                          00000000" 
7" 20-NOV-25 19:22:36 " JOG -013 Stroke limit (G:1 A:5)                   " " WARN                          00000000" 
8" 20-NOV-25 19:22:16 " JOG -013 Stroke limit (G:1 A:5)                   " " WARN                          00000000" 
9" 20-NOV-25 19:22:14 " JOG -013 Stroke limit (G:1 A:5)                   " " WARN                          00000000" 
10" 20-NOV-25 19:18:46 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
11" 20-NOV-25 19:04:54 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
12" 20-NOV-25 18:46:40 " SRVO-307 HBK close/HBK enabled (G:1)              " " WARN                          00000000" 
