ERRMOT.LS      Robot Name ROBOT 20-NOV-25 07:50:40  

1" 20-NOV-25 07:50:02 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
2" 20-NOV-25 07:43:32 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
3" 19-NOV-25 15:13:06 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
4" 19-NOV-25 14:44:58 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
5" 19-NOV-25 14:16:26 " SRVO-307 HBK close/HBK enabled (G:1)              " " WARN                          00000000" 
